basketsapp/urls.py
from django.urls import path

from basketsapp.views import basket_add, basket_remove, basket_edit

app_name = 'baskets'

urlpatterns = [
    path('add/<int:product_id>/', basket_add, name='basket_add'),
    path('remove/<int:basket_id>/<int:product_id>/', basket_remove, name='basket_remove'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

buyersapp/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from buyersapp.views import BuyerLoginView, BuyerRegistrationView, BuyerProfileView, BuyerLogoutView

app_name = 'buyersapp'

urlpatterns = [
    path('login/', BuyerLoginView.as_view(), name='login'),
    path('registration/', BuyerRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>', login_required(BuyerProfileView.as_view()), name='profile'),
    path('logout/', BuyerLogoutView.as_view(), name='logout'),
]

chop/urls.py
"""chop URL Configuration"""

from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

from productsapp.views import MainPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPageView.as_view(), name='index'),
    path('products/', include('productsapp.urls', namespace='products')),
    path('buyers/', include('buyersapp.urls', namespace='buyers')),
    path('baskets/', include('basketsapp.urls', namespace='baskets')),
    path('admins/', include('adminsapp.urls', namespace='admins')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productsapp/urls.py
from django.urls import path

from productsapp.views import ProductListView, ProductCategoryListView

app_name = 'productsapp'

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('<slug:category_slug>/', ProductCategoryListView.as_view(), name='category'),
    # path('page/<int:page>/', products, name='page')
]

productsapp/models.py
from django.db import models
from django.urls import reverse


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание категории', blank=True)
    slug = models.SlugField(max_length=60, unique=True, db_index=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_name', kwargs={'slug': self.slug})

    @property
    def products_count(self):
        products = Product.objects.filter(category=self.id).count
        return products


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, verbose_name='категории', on_delete=models.PROTECT)
    image = models.ImageField(upload_to='products_images', blank=True, null=True)
    name = models.CharField(verbose_name='имя продукта', max_length=256)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активно', default=True)

    def __str__(self):
        return f'{self.name} | {self.category}'

productsapp/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from productsapp.models import ProductCategory, Product


class MainPageView(TemplateView):
    extra_context = {'title': 'Chop'}
    template_name = 'productsapp/index.html'


# def index(request):
#     context = {
#         'title': 'Chop'
#     }
#     return render(request, 'productsapp/index.html', context)


class ProductListView(ListView):
    model = Product
    context_object_name = 'products'
    extra_context = {'title': 'Chop - каталог'}
    template_name = 'productsapp/products.html'
    # allow_empty = False # редирект на стр 404

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Chop - каталог'
        context['categories'] = ProductCategory.objects.all()
        return context


class ProductCategoryListView(ProductListView):

    def get_queryset(self):
        self.category = ProductCategory.objects.get(slug=self.kwargs.get('category_slug'))
        return Product.objects.filter(category=self.category)


# def products(request, category_id=None, page=1):
#     context = {
#         'title': 'Chop - Каталог',
#         'categories': ProductCategory.objects.all()
#     }
#     if category_id:
#         products = Product.objects.filter(category_id=category_id)
#     else:
#         products = Product.objects.all()
#     paginator = Paginator(products, 3)
#     try:
#         products_paginator = paginator.page(page)
#     except PageNotAnInteger:
#         products_paginator = paginator.page(1)
#     except EmptyPage:
#         products_paginator = paginator.page(paginator.num_pages)
#     context['products'] = products_paginator
#     return render(request, 'productsapp/products.html', context)

productsapp/templates/productsapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Chop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">
                        Каталог
                        <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'buyers:profile' user.id %}">
                            {{ user.username }}
                            <i class="fas fa-user-circle"></i>
                        </a>
                    </li>
                    {% if user.is_staff or user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admins:index' %}">
                                <i class="fas fa-users-cog"></i>
                            </a>
                        </li>
                    {% endif%}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'buyers:logout' %}">
                            Выйти
                            <i class="fas fa-sign-in-alt"></i>
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'buyers:login' %}">
                            Войти
                            <i class="fas fa-sign-in-alt"></i>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %} {% endblock %}

<!-- Footer -->
{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

<!-- JS -->
<script src="{% static 'js/basket.js' %}"></script>
{% block JS %} {% endblock%}

</body>
</html>

productsapp/templates/productsapp/index.html
{% extends 'productsapp/base.html' %}
{% load static %}
{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">Chop Store</h1>
                    <p>
                        Новые образы и лучшие бренды на Chop Store.
                        Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'products:index' %}">
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

productsapp/templates/productsapp/products.html
{% extends 'productsapp/base.html' %}
{% load static %}
{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">Chop</h1>
                <div class="list-group">
                    {% for category in categories %}
                        <a href="{% url 'products:category' category.slug %}" class="list-group-item">{{ category.name }}</a>
                    {% endfor %}
                    <a href="{% url 'products:index' %}" class="list-group-item text-success">Сбросить фильтр</a>
                </div>
            </div>
            <div class="col-lg-9">
                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}" alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}" alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <div class="row">
                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    <img class="card-img-top"
                                         src="{{ product.image.url }}" alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="#">{{ product.name }}</a>
                                    </h4>
                                    <h5>{{ product.price }} руб.</h5>
                                    <p class="card-text">{{ product.description }}</p>
                                    <h5>В наличии: {{ product.quantity }} ед.</h5>
                                </div>
                                <div class="card-footer text-center">
                                    {% if product.quantity %}
                                        <a href="{% url 'baskets:basket_add' product.id %}" class="btn btn-outline-success">Отправить в корзину</a>
                                    {% else %}
                                        <a href="#" class="btn btn-outline-error">Нет в наличии</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not products.has_previous %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if products.has_previous %} {% url 'products:page' products.previous_page_number %} {% else %} # {% endif %}"
                               tabindex="-1" aria-disabled="true">
                                Предыдущая
                            </a>
                        </li>
                        {% for page in products.paginator.page_range %}
                            <li class="page-item">
                                <a class="page-link" href="{% url 'products:page'  page %}">
                                 {{ page }}
                                </a>
                            </li>
                        {% endfor %}
                        <li class="page-item {% if not products.has_next %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if products.has_next %} {% url 'products:page' products.next_page_number %} {% else %} # {% endif %}">
                                Следующая
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Chop 2022</p>
        </div>
    </footer>
{% endblock %}