adminsapp/urls.py
from django.urls import path

from adminsapp.views import AdminPanelView, AdminBuyerListView, AdminBuyerCreateView, AdminBuyerUpdateView, \
    AdminBuyerChangeActivityView, AdminProductListView, AdminProductCreateView, AdminProductUpdateView, \
    AdminProductDeleteView, AdminCategoryListView, AdminCategoryCreateView, AdminCategoryUpdateView, AdminCategoryDeleteView

app_name = 'adminsapp'

urlpatterns = [
    path('', AdminPanelView.as_view(), name='index'),

    path('buyers/', AdminBuyerListView.as_view(), name='buyers'),
    path('buyer-create/', AdminBuyerCreateView.as_view(), name='buyer_create'),
    path('buyer-update/<int:pk>/', AdminBuyerUpdateView.as_view(), name='buyer_update'),
    path('buyer-change-activity/<int:pk>/', AdminBuyerChangeActivityView.as_view(), name='buyer_change_activity'),

    path('products/', AdminProductListView.as_view(), name='products'),
    path('product-create/', AdminProductCreateView.as_view(), name='product_create'),
    path('product-update/<int:pk>/', AdminProductUpdateView.as_view(), name='product_update'),
    path('product-delete/<int:pk>/', AdminProductDeleteView.as_view(), name='product_delete'),

    path('categories/', AdminCategoryListView.as_view(), name='categories'),
    path('category-create/', AdminCategoryCreateView.as_view(), name='category_create'),
    path('category-update/<int:pk>/', AdminCategoryUpdateView.as_view(), name='category_update'),
    path('category-delete/<int:pk>/', AdminCategoryDeleteView.as_view(), name='category_delete'),
]

chop/urls.py
"""chop URL Configuration"""

from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

from productsapp.views import MainPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPageView.as_view(), name='index'),
    path('products/', include('productsapp.urls', namespace='products')),
    path('buyers/', include('buyersapp.urls', namespace='buyers')),
    path('baskets/', include('basketsapp.urls', namespace='baskets')),
    path('admins/', include('adminsapp.urls', namespace='admins')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminsapp/models.py
from django.db import models

# Create your models here.

adminsapp/forms.py
from django import forms

from buyersapp.forms import BuyerRegistrationForm, BuyersProfileForm
from buyersapp.models import Buyer
from productsapp.models import Product
from productsapp.models import ProductCategory


class AdminBuyerRegistrationForm(BuyerRegistrationForm):
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input'}), required=False)

    class Meta:
        model = Buyer
        fields = ('username', 'email', 'avatar', 'first_name', 'last_name', 'age', 'password1', 'password2')


class AdminBuyersProfileForm(BuyersProfileForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'readonly': False}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 'readonly': False}))


class AdminProductCreateForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    price = forms.DecimalField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    quantity = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input'}), required=False)
    category = forms.ModelChoiceField(queryset=ProductCategory.objects.all(), widget=forms.Select(
        attrs={'class': 'form-control form-select pt-3 pb-2', 'size': 1}))

    class Meta:
        model = Product
        fields = ('name', 'description', 'price', 'quantity', 'image', 'category')


class AdminProductChangeForm(AdminProductCreateForm):
    pass


class AdminCategoryCreateForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}), required=False)

    class Meta:
        model = ProductCategory
        fields = ('name', 'description')


class AdminCategoryChangeForm(AdminCategoryCreateForm):
    pass

adminsapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.db.models.deletion import ProtectedError
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator

from buyersapp.models import Buyer
from productsapp.models import Product, ProductCategory
from adminsapp.forms import AdminBuyerRegistrationForm, AdminBuyersProfileForm, AdminProductCreateForm, \
    AdminProductChangeForm, AdminCategoryCreateForm, AdminCategoryChangeForm


class AdminPanelView(TemplateView):
    """ A view for displaying a admin panel """
    extra_context = {'title': 'Chop - Админ-панель'}  # replaces get_context_data
    template_name = 'adminsapp/index.html'

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super(AdminPanelView, self).dispatch(request, *args, **kwargs)

    # def get_context_data(self, **kwargs):
    #     context = super(AdminPanelView, self).get_context_data(**kwargs)
    #     context['title'] = 'Chop - Админ-панель'
    #     return context


""" BUYERS """


class AdminBuyerListView(ListView):
    model = Buyer
    extra_context = {'title': 'Chop - Покупатели'}
    template_name = 'adminsapp/buyers/admin-buyers.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(AdminBuyerListView, self).dispatch(request, *args, **kwargs)


class AdminBuyerCreateView(CreateView):
    model = Buyer
    form_class = AdminBuyerRegistrationForm
    success_url = reverse_lazy('admins:buyers')
    extra_context = {'title': 'Chop - Создание покупателей'}
    template_name = 'adminsapp/buyers/admin-buyer-create.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(AdminBuyerCreateView, self).dispatch(request, *args, **kwargs)

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def post(self, request, *args, **kwargs):
        messages.success(request, 'Пользователь успешно создан!')
        return super(AdminBuyerCreateView, self).post(request, *args, **kwargs)


class AdminBuyerUpdateView(UpdateView):
    model = Buyer
    form_class = AdminBuyersProfileForm
    extra_context = {'title': 'Chop - Редактирование покупателей'}
    template_name = 'adminsapp/buyers/admin-buyer-update-delete.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(AdminBuyerUpdateView, self).dispatch(request, *args, **kwargs)

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def post(self, request, *args, **kwargs):
        messages.success(request, 'Данные пользователя успешно изменены!')
        return super(AdminBuyerUpdateView, self).post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('admins:buyer_update', args=(self.object.id,))


class AdminBuyerChangeActivityView(DeleteView):
    model = Buyer
    success_url = reverse_lazy('admins:buyers')
    template_name = 'adminsapp/buyers/admin-buyer-update-delete.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(AdminBuyerChangeActivityView, self).dispatch(request, *args, **kwargs)

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def post(self, request, *args, **kwargs):
        messages.success(request, 'Пользователь успешно изменён!')
        return super(AdminBuyerChangeActivityView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        """ overwritten delete method """
        success_url = self.get_success_url()
        self.object.change_activity()
        return HttpResponseRedirect(success_url)


""" PRODUCTS """


class AdminProductListView(ListView):
    model = Product
    extra_context = {'title': 'Chop - Товары'}
    template_name = 'adminsapp/products/admin-products.html'

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super(AdminProductListView, self).dispatch(request, *args, **kwargs)


class AdminProductCreateView(CreateView):
    model = Product
    form_class = AdminProductCreateForm
    success_url = reverse_lazy('admins:products')
    extra_context = {'title': 'Chop - Создание товаров'}
    template_name = 'adminsapp/products/admin-product-create.html'

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super(AdminProductCreateView, self).dispatch(request, *args, **kwargs)

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def post(self, request, *args, **kwargs):
        messages.success(request, 'Продукт успешно создан!')
        return super(AdminProductCreateView, self).post(request, *args, **kwargs)


class AdminProductUpdateView(UpdateView):
    model = Product
    form_class = AdminProductChangeForm
    success_url = reverse_lazy('admins:products')
    extra_context = {'title': 'Chop - Редактирование товаров'}
    template_name = 'adminsapp/products/admin-product-update-delete.html'

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super(AdminProductUpdateView, self).dispatch(request, *args, **kwargs)

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def post(self, request, *args, **kwargs):
        messages.success(request, 'Продукт успешно изменён!')
        return super(AdminProductUpdateView, self).post(request, *args, **kwargs)


class AdminProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('admins:products')
    template_name = 'adminsapp/products/admin-product-update-delete.html'

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super(AdminProductDeleteView, self).dispatch(request, *args, **kwargs)

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def post(self, request, *args, **kwargs):
        messages.success(request, 'Продукт успешно удалён совсем!')
        return super(AdminProductDeleteView, self).post(request, *args, **kwargs)


""" CATEGORY """


class AdminCategoryListView(ListView):
    model = ProductCategory
    extra_context = {'title': 'Chop - Категории товаров'}
    template_name = 'adminsapp/categories/admin-categories.html'

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super(AdminCategoryListView, self).dispatch(request, *args, **kwargs)


class AdminCategoryCreateView(CreateView):
    model = ProductCategory
    form_class = AdminCategoryCreateForm
    success_url = reverse_lazy('admins:categories')
    extra_context = {'title': 'Chop - создание категорий товаров'}
    template_name = 'adminsapp/categories/admin-category-create.html'

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super(AdminCategoryCreateView, self).dispatch(request, *args, **kwargs)

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def post(self, request, *args, **kwargs):
        messages.success(request, 'Категория успешно создана!')
        return super(AdminCategoryCreateView, self).post(request, *args, **kwargs)


class AdminCategoryUpdateView(UpdateView):
    model = ProductCategory
    form_class = AdminCategoryChangeForm
    success_url = reverse_lazy('admins:categories')
    extra_context = {'title': 'Chop - редактирование статьи'}
    template_name = 'adminsapp/categories/admin-category-update-delete.html'

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super(AdminCategoryUpdateView, self).dispatch(request, *args, **kwargs)

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def post(self, request, *args, **kwargs):
        messages.success(request, 'Категория успешно отредактирована!')
        return super(AdminCategoryUpdateView, self).post(request, *args, **kwargs)


class AdminCategoryDeleteView(DeleteView):
    model = ProductCategory
    success_url = reverse_lazy('admins:categories')
    template_name = 'adminsapp/categories/admin-category-update-delete.html'

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super(AdminCategoryDeleteView, self).dispatch(request, *args, **kwargs)

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def post(self, request, *args, **kwargs):
        try:
            result = super(AdminCategoryDeleteView, self).post(request, *args, **kwargs)
            messages.success(request, 'Категория успешно удалена совсем!')
        except ProtectedError:
            messages.success(request, 'В категории остались продукты, удалите сначала их,'
                                                     ' или перенесите в другую категорию!')
            return HttpResponseRedirect(self.success_url)
        return result

    # from django.urls import reverse


# @user_passes_test(lambda u: u.is_staff)
# def index(request):
#     context = {'title': 'Chop - Админ-панель'}
#     return render(request, 'adminsapp/index.html', context)


""" Buyer LIST """
# @user_passes_test(lambda u: u.is_superuser)
# def admin_buyers(request):
#     context = {
#         'title': 'Chop - Покупатели',
#         'buyers': Buyer.objects.all()
#     }

adminsapp/templates/adminsapp/categories/admin-categories.html
{% extends 'adminsapp/base.html' %}
{% block content %}
    <main>
        <div class="container-fluid">
            {% if messages or form.errors %}
                <div class="alert {% if messages %} alert-success {% else %} alert-warning {% endif %} alert-dismissible fade show" role="alert"
                     style="margin-top: 50px;">
                    {% if messages %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    {% else %}
                        {% for error in form.non_field_errors %}
                            {{ error }}
                        {% endfor %}
                    {% endif %}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
            <h1 class="mt-4">Категории товаров</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Категории товаров
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Наименование</th>
                                <th>Товаров в категории</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                 <th>Наименование</th>
                                <th>Товаров в категории</th>
                            </tr>
                            </tfoot>
                            <tbody>
                                {% for category in object_list %}
                                    <tr>
                                        <td><a href="{% url 'admins:category_update' category.id %}" style="color: dodgerblue">{{ category.name }}</a></td>
                                        <td>{{ category.products_count }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'admins:category_create' %}">
                        <button class="btn btn-success">Создать категорию</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

adminsapp/templates/adminsapp/categories/admin-category-create.html
{% extends 'adminsapp/base.html' %}
{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Создание категории товаров</h1>
            <form action="{% url 'admins:category_create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.name.id_for_label }}">Наименование</label>
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                            {{ form.description }}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </main>
{% endblock %}

adminsapp/templates/adminsapp/categories/admin-category-update-delete.html
{% extends 'adminsapp/base.html' %}
{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Редактирование категории | {{ productcategory.name }}</h1>
            <div class="card-body">
                <form action="{% url 'admins:category_update' productcategory.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Наименование</label>
                                {{ form.name }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <div class="row">
                    <div class="col-lg-6" style="margin-top: 33px;">
                        <form action="{% url 'admins:category_delete' productcategory.id %}" method="post">
                            {% csrf_token %}
                            <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}